build:
  environment:
    python: 3.9.5
  dependencies:
    override:
      - pip install -q flake8
  tests:
    override:
      - flake8
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  paths:
    - niapy/*
