build:
  environment:
    python: 3.9.5
  dependencies:
    override:
      - pip install -q flake8
  tests:
    stop_on_failure: false
    override:
      - flake8 --exclude examples,docs/source/conf.py
checks:
  python:
    code_rating: true
    duplicate_code: true
filter:
  paths:
    - niapy/*
