{% set pyproject = load_file_data('pyproject.toml') %}
{% set poetry = pyproject.get('tool', {}).get('poetry') %}

package:
  name: {{ poetry.get('name') }}
  version: {{ poetry.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.9,<3.14
    - pip
    - poetry-core >=1.0.0
    - setuptools
    - wheel
  run:
    - python >=3.9,<3.14
    - numpy >=1.26.1
    - pandas >=2.1.1
    - openpyxl >=3.1.2
    - matplotlib >=3.8.0

about:
  home: {{ poetry.get('homepage') }}
  license: {{ poetry.get('license') }}
  license_file: LICENSE
  license_url: https://github.com/NiaOrg/NiaPy/blob/master/LICENSE
  summary: {{ poetry.get('description') }}
  doc_url: {{ poetry.get('documentation') }}
  dev_url: {{ poetry.get('repository') }}