{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set project_urls = project.get('urls', {}) %}

package:
  name: {{ project.get('name') }}
  version: {{ project.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.11
    - pip
    - uv_build >=0.9.17,<0.10.0
  run:
    - python >=3.11
    - numpy >=2.3.5
    - pandas >=2.3.3
    - openpyxl >=3.1.5
    - matplotlib >=3.10.8

about:
  home: {{ project_urls.get('Homepage') }}
  license: {{ project.get('license') }}
  license_file: LICENSE
  license_url: https://github.com/NiaOrg/NiaPy/blob/master/LICENSE
  summary: {{ project.get('description') }}
  doc_url: {{ project_urls.get('Documentation') }}
  dev_url: {{ project_urls.get('Repository') }}