name: All Tests

on: [workflow_dispatch, push]

jobs:
  all_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6]
    env:
      MPLBACKEND: "agg"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      run: |
        python3 -m pip install --upgrade pip
        pip install pipenv
    - name: Cache dependencies
      id: cache-dependencies
      uses: tespkg/actions-cache@v1
      with:
        endpoint: s3.eu-central-1.wasabisys.com
        insecure: false
        accessKey: ${{ secrets.S3_ACCESS_KEY }}
        secretKey: ${{ secrets.S3_SECRET_KEY }}
        bucket: niapy-actions-cache
        use-fallback: false
        key: ${{ matrix.os }}_py${{ matrix.python-version }}-Pipfile_${{ hashFiles('**/Pipfile') }}
        path: |
          .venv
        restore-keys: |
          ${{ matrix.os }}_py${{ matrix.python-version }}-Pipfile_
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        pipenv install --skip-lock --dev
    - name: Run all tests
      run: |
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8
        pipenv run pytest -ra -vv --random --random-seed=32786 --cov=niapy --no-cov-on-fail --cov-report=term-missing:skip-covered niapy niapy/tests/test_aba.py --junitxml=xmlreport/overall.xml
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        # project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        # or
        api-token: b8fc77c78d904f2cb5fbc113bfb9d6f4 # ${{ secrets.CODACY_API_TOKEN }}
        coverage-reports: xmlreport/overall.xml